networks:
  influxdb:

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
      - '8090:8090'
      - '2003:2003'
    networks:
      - influxdb
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      - ./data/influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./data/json-logging:/data/json-logging
    user: '1000:1000'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - influxdb
    env_file:
      - 'env.grafana'
    user: '0'
    links:
      - influxdb
    volumes:
      # Data persistency
      - ./data/grafana:/var/lib/grafana
